### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by yucho123987** [hu60t/hu60wap6#20]
使用Adminer和PHPMyAdmin导入mysql.sql文件时均会出现以下错误，无法导入：
查询出错 (1101): BLOB/TEXT column 'review_log' can't have a default value
此时访问首页，提示：
错误代码：500
错误信息：数据库错误，表hu60_bbs_topic_meta不可读
错误发生在 ***/class/bbs.php 的第 690 行
错误追踪信息：
#0 ***/page/index/index.php(12): bbs->newTopicList(21, 0, 'WHERE ctime>163...')
#1 ***/q.php(79): include('***')
#2 {main}
MySQL版本：5.5.62
PHP版本：7.2

**Comment by SwimmingTiger** [comment]
需要 MariaDB 10。

https://github.com/hu60t/hu60wap6/blob/227f68b7ad68e2d2bed1f785d3386c44fc3cb090/src/db/mysql.sql#L7

**Comment by YihaoPeng** [comment]
已经把支持和不支持的MySQL版本写入了文档，并给出了不支持的理由。

https://github.com/hu60t/hu60wap6/blob/8c530cff3ae46cfa5828865e06fef96c9b95cd56/README.md#%E6%94%AF%E6%8C%81%E7%9A%84mysql%E7%89%88%E6%9C%AC

**Comment by YihaoPeng** [comment]
建表语句已经更新，不再在`text`字段上设置默认值。现在应该兼容旧版MySQL了。
