### ISSUE TITLE
add support for Huawei DN8245V-56 PLEASE !

### ISSUE THREAD

**Issue by isslam95** [hu60t/hu60wap6#28]

**Comment by isslam95** [comment]
CONFIG file can be found here https://www.mediafire.com/file/3rz0q5a8xpm1f9f/Original.xml/file

**Comment by SwimmingTiger** [comment]
Sorry, this is my website project, it is not a Huawei configuration file decryption tool.

You might try to find a Huawei configuration file decryption tool like this:

https://www.google.com/search?q=site%3Agithub.com+%E5%8D%8E%E4%B8%BA+xml+%E8%A7%A3%E5%AF%86

**Comment by SwimmingTiger** [comment]
I've tried several decryption tools I can find, but none of them can decrypt your file.

**Comment by insoxin** [comment]
看了他个人主页,我感觉他翻译错了,,,这里是可以讲中文的
