### ISSUE TITLE
数据库导入失败

### ISSUE THREAD

**Issue by istrwei** [hu60t/hu60wap6#3]
错误
SQL 查询：
`CREATE TABLE IF NOT EXISTS `hu60_addin_chat_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `room` varchar(32) NOT NULL,
  `lid` int(11) NOT NULL,
  `uid` int(11) NOT NULL,
  `uname` varchar(16) NOT NULL,
  `content` blob,
  `time` bigint(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT DEFAULT CHARSET=utf8;`

MySQL 返回： 文档
`#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT CHARSET=utf8' at line 10 `

**Comment by SwimmingTiger** [comment]
ENGINE=MyISAM AUTO_INCREMENT DEFAULT CHARSET=utf8;
把这个AUTO_INCREMENT去掉，变成：
[code=sql]
CREATE TABLE IF NOT EXISTShu60_addin_chat_data( idint(11) NOT NULL AUTO_INCREMENT, roomvarchar(32) NOT NULL, lidint(11) NOT NULL, uidint(11) NOT NULL, unamevarchar(16) NOT NULL, contentblob, timebigint(20) NOT NULL, PRIMARY KEY (id) ) ENGINE=MyISAM DEFAULT CHARSET=utf8;
[/code]
我也不知道那里怎么会有一个AUTO_INCREMENT的。。。

**Comment by SwimmingTiger** [comment]
想起来了。那里本来是`AUTO_INCREMENT 5`之类的，表示自增到某个值了。我把值删掉了，忘记把`AUTO_INCREMENT`也删掉了。

**Comment by istrwei** [comment]
哦哦，好的，昨晚上搞了一晚上都没弄好
