### ISSUE TITLE
Trojan.Malware.121218.susgen

### ISSUE THREAD

**Issue by ryancoolround** [hu60t/hu60wap6#42]
Virustotal is fighting
https://www.virustotal.com/gui/file-analysis/MGQ2YzIwYTE4ZmY1ZjRkMWEyYWQyZWFjMDViMTY2OGU6MTY4MzQ1NDI3OA==

**Comment by SwimmingTiger** [comment]
So MaxSecure should be suggested to remove from VirusTotal vendor.

It's so timid that fear my Spanish captcha dictionary.

https://github.com/hu60t/hu60wap6/blob/master/src/class/SimpleCaptcha/tools/dictionary-import/sample-words-es.txt

![image](https://user-images.githubusercontent.com/4986069/236674210-3143aad5-86e5-4400-ad61-0a62c87bc1bc.png)
![image](https://user-images.githubusercontent.com/4986069/236674222-4d87bf9a-b18a-4b31-87c3-de29152b36f7.png)
